// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-KMkY2hky2ohhhjRgM83ChTfIMBnhgKA',
    appId: '1:342237332039:web:cb3a331996d6cbc81fa762',
    messagingSenderId: '342237332039',
    projectId: 'hili-helpers',
    authDomain: 'hili-helpers.firebaseapp.com',
    storageBucket: 'hili-helpers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYZSyC-bMqGc-FFmGkeu8sNGlCGOakvo',
    appId: '1:342237332039:android:4499732ed4a79f4b1fa762',
    messagingSenderId: '342237332039',
    projectId: 'hili-helpers',
    storageBucket: 'hili-helpers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrWjlrftmS1FNAu2UdmmRv9CDpdAN_J0',
    appId: '1:342237332039:ios:30e6175a4b0cb9a31fa762',
    messagingSenderId: '342237332039',
    projectId: 'hili-helpers',
    storageBucket: 'hili-helpers.appspot.com',
    iosBundleId: 'com.example.hiliHelpers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGrWjlrftmS1FNAu2UdmmRv9CDpdAN_J0',
    appId: '1:342237332039:ios:0e3d9cbc847574091fa762',
    messagingSenderId: '342237332039',
    projectId: 'hili-helpers',
    storageBucket: 'hili-helpers.appspot.com',
    iosBundleId: 'com.example.hiliHelpers.RunnerTests',
  );
}
